FROM python:3.13-slim-bookworm
LABEL MAINTAINER="Adam Hurm" INFO="Discord Super Pal of the Week"

WORKDIR /super-pal

ADD src /super-pal
ADD requirements.txt /super-pal

RUN pip install -r requirements.txt

CMD ["python", "bot.py"]
