FROM python:3.10-slim-buster
LABEL MAINTAINER="Adam Hurm" INFO="Discord Super Pal of the Week"

WORKDIR /super-pal

COPY ./src/ .
COPY requirements.txt .

RUN pip install -r requirements.txt

CMD ["python", "/super-pal/src/bot.py"]