apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    app: super-pal
  name: super-pal
  namespace: discord
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: super-pal
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: super-pal
    spec:
      containers:
      - name: super-pal-container
        image: adamhurm/discord-super-pal:latest
        imagePullPolicy: Never
        resources:
          limits:
            cpu: 1.0
            memory: 128Mi
      - name: spin-the-wheel-container
        image: adamhurm/discord-spin-the-wheel:latest
        imagePullPolicy: Never
        resources:
          limits:
            cpu: 1.0
            memory: 128Mi
      restartPolicy: Always
      terminationGracePeriodSeconds: 30