apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    app.kubernetes.io/instance: super-pal
  name: super-pal
  namespace: discord
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: super-pal
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: super-pal
    spec:
      containers:
      - name: super-pal
        image: adamhurm/discord-super-pal:1.4.0
        imagePullPolicy: Always
        env:
          - name: SUPERPAL_TOKEN
            valueFrom:
              secretKeyRef:
                name: super-pal-env
                key: super-pal-discord-key
          - name: OPENAI_API_KEY
            valueFrom:
              secretKeyRef:
                name: super-pal-env
                key: openai-api-key
          - name: GUILD_ID
            valueFrom:
              secretKeyRef:
                name: super-pal-env
                key: guild-id
          - name: CHANNEL_ID
            valueFrom:
              secretKeyRef:
                name: super-pal-env
                key: channel-id
          - name: EMOJI_GUILD_ID
            valueFrom:
              secretKeyRef:
                name: super-pal-env
                key: emoji-guild-id
          - name: ART_CHANNEL_ID
            valueFrom:
              secretKeyRef:
                name: super-pal-env
                key: art-channel-id
          - name: VOICE_CHANNELS
            valueFrom:
              secretKeyRef:
                name: super-pal-env
                key: voice-channels
          - name: GPT_ASSISTANT_ID
            valueFrom:
              secretKeyRef:
                name: super-pal-env
                key: gpt-assistant-id
          - name: GPT_ASSISTANT_THREAD_ID
            valueFrom:
              secretKeyRef:
                name: super-pal-env
                key: gpt-assistant-thread-id
      - name: spin-the-wheel
        image: adamhurm/discord-spin-the-wheel:1.0.0
        imagePullPolicy: Always
        env:
          - name: WHEEL_TOKEN
            valueFrom:
              secretKeyRef:
                name: super-pal-env
                key: spin-the-wheel-discord-key
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
